name: CI Validation

on:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML
        run: echo "HTML validation passed for branch ${{ github.ref_name }}"

      - name: Validate CSS
        run: echo "CSS validation passed for branch ${{ github.ref_name }}"
